# Generated by Django 3.1 on 2021-05-11 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20210425_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentassign',
            name='specialty',
        ),
    ]
