// User module
export const USERS_PROFILE = 'USERS_PROFILE'
export const USERS_UPDATE = 'USERS_UPDATE'
export const USERS_LIST = 'SET_USERS'
export const USERS_FILTER = 'FILTER_USERS'
export const USERS_SEND_MAILS = 'USERS_SEND_MAILS'

// Email module
export const EMAIL_SENDED = 'EMAIL_SENDED'
export const EMAIL_SENDED_FILTER = 'EMAIL_SENDED_FILTER'

// Appointment module
export const APPOINTMENT_LIST = 'SET_APPOINTMENT'
export const APPOINTMENT_CREATE = 'APPOINTMENT_CREATE'
export const APPOINTMENT_FILTER = 'APPOINTMENT_FILTER'
export const APPOINTMENT_DELETE = 'APPOINTMENT_DELETE'
export const APPOINTMENT_DELETED_LIST = 'APPOINTMENT_DELETED_LIST'
export const APPOINTMENT_DAY = 'APPOINTMENTS_DAY'
export const APPOINTMENT_DELETED_NOTIFICATION =
  'APPOINTMENT_DELETED_NOTIFICATION'
export const APPOINTMENT_DELETED_NOTIFICATION_DELETE =
  'APPOINTMENT_DELETED_NOTIFICATION_DELETE'

// Specialty module
export const SPECIALTY_LIST = 'SPECIALTY_LIST'
export const SPECIALTY_DELETE = 'SPECIALTY_DELETE'
export const SPECIALTY_FILTER = 'SPECIALTY_FILTER'

// Notification admin
export const ADMIN_APPOINTMENT_DELETED = 'ADMIN_APPOINTMENT_DELETED'
